Remove dublicate modules paths - use only first occurences
regru/bem-loader pull request #3
Opened 2018-04-25 12:08 UTC by greatbigsled

2018-04-25 14:23 UTC, shifteee requested changes
to much cycles. Please use reducers

And I can't see any priority of paths.

2018-04-25 14:23 UTC, shifteee commented on libs/search.js
> +            matches = dedupMatches(matches);
we should not reassign function parameters

2018-04-25 14:25 UTC, podkot commented on libs/search.js
> +            matches = dedupMatches(matches);
maybe we should move our eslint configs to github? to include em in all the projects

2018-04-25 14:30 UTC, shifteee commented on libs/search.js
> +            matches = dedupMatches(matches);
yep . I can do it

2018-04-25 21:26 UTC, podkot commented
@str1x take a look pls, as a part of cross-review practice

2018-04-26 07:10 UTC, greatbigsled commented
> to much cycles. Please use reducers
done

> And I can't see any priority of paths
Yes, it looks like levels order doesn't matter for glob.

2018-04-26 07:54 UTC, greatbigsled commented
>And I can't see any priority of paths

Adding `nosort` flag to glob seems to help

2018-04-26 07:57 UTC, shifteee reviewed
I still can't see any solutions of our problem. First occurrence could be any: bem/, node_modules/, src/, etc.  But, as i can understand, it's not our goal . We should manage this behavior either from passed option or by adhering priority of levels

2018-04-26 07:57 UTC, shifteee commented on libs/search.js
> +function getFileName(path) {
I suggest you use native nodejs [path](https://nodejs.org/api/path.html) module .

2018-04-27 12:08 UTC, greatbigsled commented
Are we done here?

2018-04-27 12:12 UTC, podkot approved these changes

2018-04-27 13:15 UTC, str1x commented
lgtm

2018-04-27 15:00 UTC, shifteee commented
Ok, i checked source code of glob. nd it seems you're right. So we need last 2 thing: test and documentation

2018-05-04 07:17 UTC, greatbigsled commented
Added tests.
Added some info to readme.

2018-05-04 14:32 UTC, shifteee approved these changes

2018-05-04 16:14 UTC, merged